name: Build and upload zip installer to assets

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

permissions:
  id-token: write
  contents: write
  packages: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_ENV
          sed -i "s/<version>/$VERSION/" RomM/__version__.py

      - name: Setup just
        uses: extractions/setup-just@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run justfile
        run: |
          just clean
          just build

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: .dist/RomM\ Installer\ ${{ env.version }}.muxapp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
